In [62]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,roc_auc_score,roc_curve


In [63]:
df_final=pd.read_csv('final_data1.csv')

In [64]:
df_final.drop('Unnamed: 0',inplace=True,axis=1)

In [65]:
df_final.replace([0.0,1],[0,1])

FTI       TSH         TT4       T4U  outcome
0     111.333333  1.600000  128.000000  1.196667        0
1      95.333333  0.533333  124.333333  0.956667        0
2     106.000000  1.016667  130.666667  0.906667        0
3     116.666667  1.383333  110.666667  0.970000        1
4     128.333333  2.100000  133.333333  0.976667        0
...          ...       ...         ...       ...      ...
8776   77.000000  2.783333   64.000000  0.830000        0
8777   99.000000  0.750000   91.000000  0.920000        0
8778   89.000000  1.433333  113.000000  1.270000        1
8779   88.000000  0.780000   75.000000  0.850000        0
8780   65.000000  0.983333   66.000000  1.020000        0

[8781 rows x 5 columns]

In [66]:
df_final.head()

FTI       TSH         TT4       T4U  outcome
0  111.333333  1.600000  128.000000  1.196667        0
1   95.333333  0.533333  124.333333  0.956667        0
2  106.000000  1.016667  130.666667  0.906667        0
3  116.666667  1.383333  110.666667  0.970000        1
4  128.333333  2.100000  133.333333  0.976667        0

In [67]:
x_train, x_test, y_train, y_test = train_test_split(df_final.drop(columns="outcome"), df_final["outcome"], test_size=0.30,random_state=42)

In [68]:
x_train

FTI       TSH    TT4   T4U
7439  145.0  3.900000   90.0  0.62
2570   85.0  8.799999  106.0  1.25
6525  144.0  0.075000  157.0  1.09
4029  152.0  0.010000  127.0  0.84
6771  126.0  1.700000  113.0  0.90
...     ...       ...    ...   ...
5734  122.0  1.000000  106.0  0.87
5191  102.0  1.000000  103.0  1.01
5390  247.0  0.065000  147.0  0.60
860    98.0  0.700000   97.0  0.99
7270  109.0  3.200000   95.0  0.87

[6146 rows x 4 columns]

In [69]:
x_test

FTI   TSH    TT4   T4U
2697   84.0  5.40   75.0  0.90
3933  138.0  0.33  134.0  0.97
7316  113.0  1.30   95.0  0.84
3181  125.0  3.20  123.0  0.98
7788  114.0  3.40  106.0  0.93
...     ...   ...    ...   ...
6638  129.0  1.20  153.0  1.19
746   100.0  1.60   94.0  0.94
4094  122.0  2.30   73.0  0.60
2476  143.0  0.70  120.0  0.84
2024  105.0  0.40   94.0  0.90

[2635 rows x 4 columns]

In [70]:
y_test

2697    0
3933    0
7316    0
3181    0
7788    0
       ..
6638    1
746     1
4094    1
2476    0
2024    0
Name: outcome, Length: 2635, dtype: int64

In [71]:
dt_model=DecisionTreeClassifier()
dt_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [72]:
# clf = DecisionTreeClassifier(criterion = "entropy", random_state = 300,max_depth = 20, min_samples_leaf = .3)
# clf.fit(x_train, y_train)
# y_pred= clf.predict(x_test)
# accuracy_score(y_test,y_pred)*100

In [93]:
y_pred = dt_model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [91]:
dt_model.predict([[103.0,1.45,32.66,0.9]])

c:\Users\adity\Desktop\ineuron\ineuron-env\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [94]:
from sklearn.metrics import accuracy_score

In [95]:
accuracy_score(y_test,y_pred)

0.8314990512333966

In [74]:
dt_model.score(x_test,y_test)*100

83.14990512333966

In [ ]:
dt_model

In [75]:
dt_en=DecisionTreeClassifier(criterion='entropy')

In [76]:
dt_en.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [77]:
dt_en.score(x_test,y_test)*100

83.98481973434535

In [78]:
predict=dt_en.predict(x_test)

In [79]:
import numpy as np

In [80]:
from sklearn import linear_model

In [81]:
logr = linear_model.LogisticRegression()
logr.fit(x_train,y_train)

LogisticRegression()

In [82]:
logr.predict(x_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [83]:
logr.score(x_test,y_test)*100

82.08728652751424

In [84]:
import xgboost as xgb

In [85]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.7, learning_rate = 0.1,
                max_depth = 10, alpha = 1, n_estimators = 500)

In [86]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.9, learning_rate = 0.1,
                max_depth = 10, alpha = .5, n_estimators = 500)

In [87]:
xg_reg.fit(x_train,y_train)

[13:28:19] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-08de971ced8a8cdc6-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(alpha=0.5, base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=500, n_jobs=None, num_parallel_tree=None,
             objective='reg:linear', ...)

In [88]:
xg_reg.score(x_train,y_train)*100

95.25299215077949